version: 2
jobs:
  build:
    docker:
      - image: previousnext/php-apache:7.3-3.x-dev
    working_directory: /data
    steps:
      - checkout
      - run: composer install --prefer-dist --no-progress --no-suggest --no-interaction --optimize-autoloader
      - run: ./bin/phpcs --colors --report=full
      - run: mkdir -p build/phpunit
      - run: ./bin/phpunit --log-junit build/phpunit
      - store_test_results:
          path: build
