version: 2
jobs:
  build:
    docker:
      - image: previousnext/php-apache:7.3-3.x-dev
    working_directory: /data
    steps:
      - checkout
      - restore_cache:
          keys:
            - deps-{{ arch }}-{{ checksum "composer.lock" }}
      - run: composer install --prefer-dist --no-progress --no-suggest --no-interaction --optimize-autoloader
      - save_cache:
          key: deps-{{ arch }}-{{ checksum "composer.lock" }}
          paths:
            - bin
            - vendor
      - run: ./bin/phpcs --colors --report=full
      - run: mkdir -p build/phpunit
      - run: ./bin/phpunit --log-junit build/phpunit
      - store_test_results:
          path: build
